---

- name: Power off a server
  community.general.hpilo_boot:
    host: "{{ ilo_ip }}"
    login: "{{ ilo_user }}"
    password: "{{ ilo_password }}"
    state: poweroff
  when: vendor|lower =="hp"
  ignore_errors: true

- pause:
    minutes: 1
  when: vendor|lower =="hp"
  
- name: Task to boot a system using an ISO from an HP iLO interface only if the system is an HP server
  community.general.hpilo_boot:
    host: "{{ ilo_ip }}"
    login: "{{ ilo_user }}"
    password: "{{ ilo_password }}"
    media: cdrom
    state: boot_once
    image: "{{ http_share }}"
  when: vendor|lower =="hp"