---

  - name: "Power off Dell Server"
    dellemc.openmanage.dellemc_change_power_state:
      idrac_ip: "{{ idrac_ip }}"
      idrac_password: "{{ idrac_password }}"
      idrac_user: "{{ idrac_user }}"
      change_power: ForceOff
    when: vendor|lower == "dell"
    ignore_errors: true

  - name: "Booting to Network Operating System image (CIFS)"
    dellemc.openmanage.idrac_os_deployment:
      idrac_ip: "{{ item.idrac_ip }}"
      idrac_password: "{{ idrac_password }}"
      idrac_user: "{{ idrac_user }}"
      share_name: "{{ cifs_share_name }}"
      share_user: "{{ cifs_share_user }}"
      share_password: "{{ cifs_share_password }}"
      iso_image: "{{ cifs_iso_image }}"        
      expose_duration: 75
    when: os_deploy_type == "cifs" and vendor|lower =="dell"

  - name: "Booting to Network Operating System image (NFS)"
    dellemc.openmanage.idrac_os_deployment:
      idrac_ip: "{{ idrac_ip }}"
      idrac_password: "{{ idrac_password }}"
      idrac_user: "{{ idrac_user }}"
      share_name: "{{ nfs_share_name }}"
      share_user: "{{ nfs_share_user }}"
      share_password: "{{ nfs_share_password }}"
      iso_image: "{{ nfs_iso_image }}"
      expose_duration: 75
    when: os_deploy_type == "nfs" and vendor|lower =="dell"